remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: DCD Research Methods -- Summer 2024 --
description: A hub for the DCD Research Methods seminar in summer 2024 
